services:
  - type: web
    name: pocketbase
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true