services:
  - type: web
    name: pocketbase
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: PORT
        value: 8080

    disk:
      name: pb-data
      mountPath: /pb_data
      sizeGB: 10
